--liquibase formatted sql

--changeset daniil:files-register-table
create table FILES_REGISTER (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    VERSION INTEGER NOT NULL DEFAULT 0,
    SIZE INTEGER NOT NULL,
    CHECKSUM VARCHAR(64),
    OWNER VARCHAR(255) NOT NULL,
    CREATED DATETIME NOT NULL,
    MODIFIED DATETIME
);